[package]
name = "multistepper"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
ufmt = "0.2.0"
ufmt-macros = "0.3.0"
winnow = { version = "0.7.2", default-features = false }

[dev-dependencies]
proptest = "1.6.0"
